"""Initial migration

Revision ID: 149e848ff258
Revises: 
Create Date: 2025-01-08 00:27:07.004988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '149e848ff258'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklisted_tokens')
    op.drop_table('token_users')
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('posts', 'reading_time')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index('auth_token', table_name='users')
    op.drop_index('idx_reset_token', table_name='users')
    op.drop_column('users', 'token_expires_at')
    op.drop_column('users', 'auth_token')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True))
    op.add_column('users', sa.Column('bio', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))
    op.add_column('users', sa.Column('auth_token', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True))
    op.add_column('users', sa.Column('token_expires_at', mysql.DATETIME(), nullable=True))
    op.create_index('idx_reset_token', 'users', ['password_reset_token'], unique=False)
    op.create_index('auth_token', 'users', ['auth_token'], unique=False)
    op.drop_column('users', 'deleted_at')
    op.add_column('posts', sa.Column('reading_time', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'deleted_at')
    op.create_table('token_users',
    sa.Column('token', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('token'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('blacklisted_tokens',
    sa.Column('token', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('blacklisted_at', mysql.DATETIME(), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('token'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
