"""Initial migration

Revision ID: 293f379a83b6
Revises: 149e848ff258
Create Date: 2025-01-08 00:43:21.365258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293f379a83b6'
down_revision = '149e848ff258'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
